[package]
name = "holo"
version = "0.1.0"
edition = "2021"
authors = ["Satoshi Amemiya <amemiya@protonmail.com"]

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
dirs = "4.0.0"
nix = { version = "0.26.1", features = ["mount", "sched", "user"] }
